"""Materialize a lens bundle into a browseable file tree — the lens-as-repo view.

A lens is stored as a ``{config, semantic_model}`` bundle in Postgres; this renders
that bundle (plus its certified definitions, eval cases, and latest drift audit) into an
ordered ``{path: content}`` map — the file tree the UI browses and the version
history diffs. Pure: no DB, no IO. Callers gather the peripheral artifacts and pass
them in.

Lens-LOCAL definitions render in the same markdown-with-frontmatter form as
certified-definition pages (``render_definition_page``), so the on-disk shape is
uniform and a reviewed definition can graduate into certified definitions without
reformatting. Shared definitions live at project scope (``semantic/``); their
compiled effect on this lens is browseable in ``compiled.yaml``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import yaml

from services.certdefs import CertifiedDefinition, render_definition_page
from services.certify.store import CertifiedAnswer, authored_status
from services.contracts.eval import parse_behavioral_marker
from services.evals.store import EvalCaseRow
from services.lenses.store import LensBundle
from services.semantic.files import definition_to_page, slug

if TYPE_CHECKING:  # AuditRun lives in the api layer; type-only to keep lenses below it.
    from services.api.audit_store import AuditRun


def _readme(bundle: LensBundle, audit: AuditRun | None) -> str:
    sm = bundle.semantic_model
    cfg = bundle.config
    lines = [
        f"# {cfg.display_name}",
        "",
        cfg.description or "_no description_",
        "",
        "> Generated by dst - this lens as a versioned repository.",
        "",
        "## Contents",
        f"- entities: {len(sm.entities)}",
        f"- definitions: {len(sm.definitions)}",
        f"- sample queries: {len(sm.sample_queries)}",
    ]
    if audit is not None:
        lines += [
            "",
            "## Freshness",
            f"- latest drift audit: {audit.created_at:%Y-%m-%d} "
            f"({audit.days}d window, {audit.records_scanned} records scanned)",
        ]
    return "\n".join(lines) + "\n"


def render_lens_repo(
    bundle: LensBundle,
    *,
    certified: list[CertifiedDefinition] | None = None,
    certified_answers: list[CertifiedAnswer] | None = None,
    eval_cases: list[EvalCaseRow] | None = None,
    audit: AuditRun | None = None,
) -> dict[str, str]:
    """Render a lens bundle (+ peripheral artifacts) into an ordered ``{path: content}``.

    Optional artifacts that are absent simply omit their files — an empty tree entry
    is never emitted. Insertion order is the browse order (README first). README and
    audit/ are runtime-only outputs the project loader ignores.
    """
    files: dict[str, str] = {}
    files["README.md"] = _readme(bundle, audit)

    # The lens's own config — the file-first source of truth for `dst apply`.
    files["lens.yaml"] = yaml.safe_dump(
        bundle.config.model_dump(mode="json", exclude_none=True),
        sort_keys=False,
        allow_unicode=True,
    )

    # The lens's own voice: router anchors + accepted question→SQL pairs.
    sm = bundle.semantic_model
    files["queries.yaml"] = yaml.safe_dump(
        {
            "use_when": sm.use_when,
            "sample_queries": [q.model_dump() for q in sm.sample_queries],
        },
        sort_keys=False,
        allow_unicode=True,
    )

    # LOCAL definitions only, as certified-format pages (uniform on-disk shape).
    # Shared terms live at project scope (semantic/definitions/) — the compiled
    # copies below in compiled.yaml are where their effect on this lens shows.
    for d in sm.definitions:
        if d.source == "shared":
            continue
        # `slug` is the shared layer's stem rule, imported rather than restated:
        # a second copy here is how a lens tree and semantic/ could ever have
        # disagreed about one asset's filename.
        files[f"definitions/{slug(d.term)}.md"] = definition_to_page(d)

    # The full compiled SemanticModel — a browseable artifact like README (the
    # loader ignores it). Shared-layer edits surface here as reviewable diffs —
    # which is why compiled_at is dropped: a per-compile timestamp would make
    # every recompile a guaranteed git diff/conflict.
    compiled = sm.model_dump(mode="json", exclude_none=True)
    if compiled.get("shared_provenance"):
        compiled["shared_provenance"].pop("compiled_at", None)
    files["compiled.yaml"] = yaml.safe_dump(compiled, sort_keys=False, allow_unicode=True)

    # The lens's certified definitions, verbatim (already certified-definition pages).
    for m in certified or []:
        files[f"certified/{slug(m.metric)}.md"] = render_definition_page(m)

    # Approved question→SQL pairs, minus their embeddings (re-derived on apply).
    # created_by/created_at are runtime provenance — stamped by the server, so an
    # applied file's pairs re-export with server values. source/verified_by are
    # OPTIONAL keys, rendered only when set (files without them stay byte-identical);
    # status renders only when retired (active is the default — active files stay
    # byte-identical); bindings are derived, DB-only, never rendered. Always
    # rendered, even empty — an authored `[]` file must not diff forever against
    # an omitted DB side.
    pairs = [
        {
            "question": a.question,
            "sql": a.sql,
            # Template keys render right after the SQL they type;
            # optional, so pre-PC files stay byte-identical.
            **({"slots": a.slots} if a.slots else {}),
            **({"sample_bindings": a.sample_bindings} if a.sample_bindings else {}),
            "created_by": a.created_by,
            "created_at": a.created_at,
            **({"source": a.source} if a.source else {}),
            **({"verified_by": a.verified_by} if a.verified_by else {}),
            **({"verified_value": a.verified_value} if a.verified_value else {}),
            # The certify-time prose — server-stamped like
            # verified_value, optional so older files stay byte-identical.
            **({"verified_prose": a.verified_prose} if a.verified_prose else {}),
            # The AUTHORED status — pending_embedding is derived server
            # state (the vector is missing), never a key a file carries.
            **({"status": a.status} if authored_status(a.status) != "active" else {}),
        }
        for a in certified_answers or []
    ]
    files["certified_answers.yaml"] = yaml.safe_dump(pairs, sort_keys=False, allow_unicode=True)

    # Like certified_answers.yaml: always rendered, even empty — the scaffold
    # ships an authored `[]` file, which must not diff forever against an
    # omitted DB side. A behavioral expectation lives in its own expect/term
    # columns (migration 0031) and renders back as the authored keys, so applied
    # files don't diff forever against their export; a pre-0031 row still
    # carrying the marker decodes on the way out (legacy read path).
    cases: list[dict[str, str | list[str] | None]] = []
    for c in eval_cases or []:
        expect, term = (
            (c.expect, c.term)
            if c.expect is not None
            else parse_behavioral_marker(c.expected_answer)
        )
        # tags render only when set — untagged files stay byte-identical, and
        # an applied tagged file round-trips its tags.
        if expect is not None:
            cases.append(
                {
                    "question": c.question,
                    "expect": expect,
                    **({"term": term} if term else {}),
                    "status": c.status,
                    "source": c.source,
                    **({"tags": list(c.tags)} if c.tags else {}),
                }
            )
        else:
            cases.append(
                {
                    "question": c.question,
                    "expected_sql": c.expected_sql,
                    "expected_answer": c.expected_answer,
                    "status": c.status,
                    "source": c.source,
                    **({"tags": list(c.tags)} if c.tags else {}),
                }
            )
    files["evals/cases.yaml"] = yaml.safe_dump(cases, sort_keys=False, allow_unicode=True)

    if audit is not None:
        files["audit/latest.json"] = audit.model_dump_json(indent=2)

    return files
